<a href="https://colab.research.google.com/github/grshprajapat/practice/blob/master/nmpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
x=np.array([[1, 2], [3, 4]])
y=np.array([[5, 6], [7, 8]])

In [0]:
v=np.array([9, 10])

In [0]:
w=np.array([11, 12])

In [0]:
print(np.dot(v,w),"\n")

219 



In [0]:
print(np.dot(x,v),"\n")

[29 67] 



In [0]:
print(np.dot(x,y))

[[19 22]
 [43 50]]


In [0]:
print(x)

[[1 2]
 [3 4]]


In [0]:
print(y)

[[5 6]
 [7 8]]


In [0]:
x*y

array([[ 5, 12],
       [21, 32]])